### ISSUE TITLE
Don't quit!

### ISSUE THREAD

**Issue by SomeGuy54321** [olivernybroe/intellij-touch#1]
Saw your comment here: https://youtrack.jetbrains.com/issue/IDEA-163208#comment=27-2798070

Don't quit! 

JetBrains' might suck and anyway it won't even be configurable when it's released in 2018.2. 

I'm gonna try to get your plugin working later.

**Comment by olivernybroe** [comment]
Hey :)

Actually just started working on the plugin today again. 
The configuration works but requires a restart of the IDE. 

The issues I am having atm. Is
- automatic update of touch bar when changing settings. 
- stability issues for showing the touch bar. Sometimes it destroys the whole UI system on Mac.
