### ISSUE TITLE
[Bug] "Preferences" button added to touch bar doesn't do anything

### ISSUE THREAD

**Issue by SomeGuy54321** [olivernybroe/intellij-touch#13]
This is a kinda great thing, I've replaced the Toolbar row on the top of the IDE with touchbar buttons, gaining some valuable centimeters.

Only issue I've noticed is that when I add the Preferences button to the touchbar, it is displayed but touching it does nothing.

This is in v4 of the plugin, installed from the IntelliJ repo. The button Action was added from "All Actions" > "Main Menu" > "File" > "Preferences". I've adding the Preferences button from other places in the "Add Actions" menu thinking that it'd make it work but it didn't.

**Comment by olivernybroe** [comment]
Hmm sounds wierd, I'll look into it tomorrow.
Thanks for the feedback.

**Comment by olivernybroe** [comment]
What IDE and version are you running?

**Comment by SomeGuy54321** [comment]
PyCharm Professional 2018.1.1

**Comment by olivernybroe** [comment]
New version is up, it should fix the problem. 
You can download it in releases or wait for IntelliJ to approve it.

**Comment by olivernybroe** [comment]
New version should be approved now.

**Comment by SomeGuy54321** [comment]
Yup that fixed it.
