### ISSUE TITLE
[Question] How to add text button?

### ISSUE THREAD

**Issue by olimsaidov** [olivernybroe/intellij-touch#15]
I want to add button with text label and no icon. Is this possible? How can I do this?

**Comment by olivernybroe** [comment]
Unfortunately we cant change what the text label says, but we can remove the icon and have a text label.

To do this add the action and press `Edit Action Icon..` and dont choose anything. This will result in a label being created with the name of the action.
Changing the name of this label is not possible, this will first be possible when our own custom UI is done.
