### ISSUE TITLE
[Bug] FindUsageAction doesn't work

### ISSUE THREAD

**Issue by dirong** [olivernybroe/intellij-touch#16]
## Expected Behavior
  1. A user adds `Find Usage` action to Touch Bar. 
  2. A user clicks the button (touch bar item) `Find Usage`
  3. Find Usage action works well and IDEA shows usages references of the subject under the mouse cursor

## Actual Behavior
  1. A user adds `Find Usage` action to Touch Bar. 
  2. A user clicks the button (touch bar item) `Find Usage`
  3. Nothing happens 

## Steps to Reproduce the Problem
  1. Add `Find Usage` action to Touch Bar. 
  3. Click the button (touch bar item) `Find Usage`

## Specifications

  - Plugin Version: 0.5
  - Platform: IDEA CE
  - Platform Version: 2018.1.2

## Tech notes
I debugged this issue on my side and found that `FindUsageAction` is called but `FindUsagesInFileAction.isEnabled` returns `false` because `CommonDataKeys.EDITOR.getData(dataContext)` returns `null`. 
So, I didn't spend enough time to investigate this issue, but I guess this relates to focus changing.

**Comment by olivernybroe** [comment]
Thanks for the feedback, I found similar behaviour with `reformat code`. Might be all actions which uses the current editor window which has this problem.

**Comment by olivernybroe** [comment]
New release is up, it should be fixed now. 
It is pending in IntelliJ plugin system but you can download it from releases on Github.

**Comment by olivernybroe** [comment]
Hope it works for you too, because I just released it :)
