### ISSUE TITLE
Where I can download latest release?

### ISSUE THREAD

**Issue by krzysztof-miemiec** [olivernybroe/intellij-touch#6]
I would like to add a plugin to WebStorm, but I can't find it in a repository. Can you add a link to prebuilt  plugin which I could install manually?

**Comment by olivernybroe** [comment]
Still waiting approval for the plugin, submitted the request yesterday.
You can find it under releases https://github.com/olivernybroe/intellij-touch/releases

**Comment by krzysztof-miemiec** [comment]
Thank you! It works with WebStorm 2018.1! 🎉

**Comment by olivernybroe** [comment]
Great! 
Then I just have to find a solution so we dont have to restart the IDE each time we change some settings.
