### ISSUE TITLE
Where is the .jar file?

### ISSUE THREAD

**Issue by joostdelange** [olivernybroe/intellij-touch#8]
To install a jetbrains plugin in one of their IDE's you need a .jar file, am I right? I can't find it in this project.

I do not have any experience with java and converting/compiling a build to an executable .jar file so I'd love to know where I can't find it or how I can make one myself.

**Comment by olivernybroe** [comment]
You can find it under releases. https://github.com/olivernybroe/intellij-touch/releases

**Comment by joostdelange** [comment]
Thank you, I loaded it.
Altough my phpstorm won't start anymore now.

This is the error I'm getting:
**Cannot load project**
`Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin dk.lost_world.intellij-touch`

Do you have an idea what this could be?

**Comment by olivernybroe** [comment]
@joostdelange Just been an update to the underlying touchbar library which changed something. I'll look into it and return to you when I have it fixed.

**Comment by olivernybroe** [comment]
@joostdelange Try installing version 0.2 instead, it seems like that version doesn't crash as it is compiled with the earlier version on the underlying touchbar library.

**Comment by olivernybroe** [comment]
@joostdelange new version is up now. 
It is indeed a bug in the touch bar library, so the newest codebase is now compiled with an older version of the touch bar library.
